services:
  eya46eya46:
    build: .
    environment:
      - WAKATIME_TOKEN=${WAKATIME_TOKEN}
      - HALO_URL=${HALO_URL}
      - HALO_TOKEN=${HALO_TOKEN}
      - HOST=0.0.0.0
    ports:
      - "4321:4321"
    container_name: eya46eya46
    network_mode: bridge
    restart: always
